export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const ADD_USERS_REQUEST = "ADD_USERS_REQUEST";
export const DELETE_USERS_REQUEST = "DELETE_USERS_REQUEST";

export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";